# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: "3Yg4A+Pcj/W6VWfwEABeZ8KE"

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: "r9Q97EHtUDih^t#2QDrJeJag"
    salt: "Dg|@(x!!@6G-tXDs$n.D/oi7o*}m;Tq62~Vk#Ewn*e0~J8/BfYjJ/D=[>)*E|zW3"

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  example.com:
    env:
      db_password: "8yKHXr9EoVJqyNgpK9;R3$xR"
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "lTXDZq7{0Z Ynp?RV{66nXrami8v.l|5Nhz;GeqWrq;^4-y~{+63XG2)]mwn-VqD"
      secure_auth_key: "Dg|@(x!!@6G-tXDs$n.D/oi7o*}m;Tq62~Vk#Ewn*e0~J8/BfYjJ/D=[>)*E|zW3"
      logged_in_key: "~(`SCoj>}-|OfXCV-PzeEl?~X;%+7i/h2&[c*Y&p^G^Ms.!oT=;n+e*r?fU&s6_u"
      nonce_key: "jO|ZZ _go=cMAz`wX[p`I;=koY0Rq:v[s|XDi<$6Z<T~(:+|>@0A(tRd;c*OpE E"
      auth_salt: "]w]3c,vK.tV3qrn_q5%Z[vJ2<5XCxnb4Wd{:}5U*YUHv7*?+w}Z.Y0AK8MT(8JNG"
      secure_auth_salt: "9F}bo^I,|}M.)gM&1o/RzK-J :0Hpl#La]!!/jn5e2N;NBsy4&t@/DYi#2hc&8eh"
      logged_in_salt: "7y6{Qb~E=q[.*z/r=oN*I/TsG>K-<%rK6l/1K>Rr$x[|>.l@g:[-.cd<mLr4$u=;"
      nonce_salt: "~~n:c0_=Y_N{B]-JN?Td&*k+|.4{q`(NxxnF6R47Q:4IbcT=0M5Y*hvz{AOiQ:~@"
